### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cengizalcan** [3a1/Zodiak#3]
Why i get this errors?  When i want compile, before ask me download WDK, i done, but still have problem...

Edit: I tried build x64 too. Same problem.

https://youtu.be/fjNVgKhsGxQ

**Comment by 3a1** [comment]
Problem that you dont have WDK kit for driver development installed.
Follow this guide:
https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by cengizalcan** [comment]
Thank you so much. It can works!

**Comment by fedecazzanigaa** [comment]
> Problem that you dont have WDK kit for driver development installed. Follow this guide: https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

Hi, sorry... I've followed that but I come across with same error.

**Comment by 3a1** [comment]
Hi, u should download the WDK kit for driver development

> > Problem that you dont have WDK kit for driver development installed. Follow this guide: https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
> 
> Hi, sorry... I've followed that but I come across with same error.

**Comment by fedecazzanigaa** [comment]
> Hi, u should download the WDK kit for driver development
> 
> > > Problem that you dont have WDK kit for driver development installed. Follow this guide: https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
> > 
> > 
> > Hi, sorry... I've followed that but I come across with same error.

Sorry, I mean... I've already done it... Do I have to "refresh" something?

**Comment by 3a1** [comment]
> > Hi, u should download the WDK kit for driver development
> > > > Problem that you dont have WDK kit for driver development installed. Follow this guide: https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
> > > 
> > > 
> > > Hi, sorry... I've followed that but I come across with same error.
> 
> Sorry, I mean... I've already done it... Do I have to "refresh" something?

Maybe u have forgot to install SDK and WDK, u need to install both
